# Generated by Django 6.0.2 on 2026-03-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0004_representative_hover_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billposition',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='billposition',
            constraint=models.UniqueConstraint(fields=('representative', 'bill_article'), name='unique_rep_bill'),
        ),
    ]
